content/posts/connecting-the-dots.md

Issue: https://github.com/UNDataForum/main-website/issues/36

Review connecting-the-dots post

---

package.json
yarn.lock

Fix hot reloading

---

.eslintrc
package.json
yarn.lock

Modify .eslintrc

---

site/package.json
site/src/@undataforum/gatsby-theme-base/components/footer.js
site/src/@undataforum/gatsby-theme-base/components/header.js
yarn.lock

Update dependency @undataforum/gatsby-theme-blog to v0.6.1

---

renovate.json

Config Renovate to group certain packages

---

site/package.json
site/src/pages/index.js

Add homepage

---

package.json
yarn.lock

Graceful dependency update

---

site/package.json
yarn.lock

Disable Gatsby telemetry

---

site/src/pages/index.js

Fix title in homepage

---

site/package.json
site/src/@undataforum/gatsby-theme-base/components/layout.js
site/src/gatsby-plugin-theme-ui/index.js
yarn.lock

Use custom font Roboto

---

package.json

Build website with Node v12 on Zeit Now

---

site/gatsby-config.js
site/src/@undataforum/gatsby-theme-base/components/header.js
site/src/pages/index.js

Rename events to webinars

---

site/gatsby-config.js
site/src/pages/about.md

Change host country reference in About page

---

site/src/@undataforum/gatsby-theme-base/pages/contact.md

Update contact info

---

site/gatsby-config.js
site/package.json
site/src/pages/about.md
yarn.lock

Fix og:title on all pages

---

site/src/components/about.js
site/src/components/experience.js
site/src/components/hero.js
site/src/gatsby-plugin-theme-ui/index.js
site/src/pages/index.js

Redesign homepage

---

site/src/pages/index.js

Fix sort order of webinars on homepage

---

renovate.json

Config Renovate Bot to do less frequent updates

---

site/content/posts/can-we-harness-the-full-power-of-data.md

Add post can-we-harness-the-full-power-of-data post

---

site/content/posts/harnessing-census-data-collection-with-citizen-participation.md

Add post harnessing-census-data-collection-with-citizen-participation

---

site/content/posts/making-data-protection-work.md

Add post making-data-protection-work

---

gatsby-theme-2020/content/thematic-areas/TA1.md
gatsby-theme-2020/content/thematic-areas/TA2.md
gatsby-theme-2020/content/thematic-areas/TA3.md
gatsby-theme-2020/content/thematic-areas/TA4.md
gatsby-theme-2020/content/thematic-areas/TA5.md
gatsby-theme-2020/content/thematic-areas/TA6.md
gatsby-theme-2020/gatsby-config.js
gatsby-theme-2020/package.json
gatsby-theme-2020/src/pages/2020/programme.js
site/src/@undataforum/gatsby-theme-base/components/header.js
yarn.lock

Add programme

---

gatsby-theme-2020/src/pages/2020/call-for-session-proposals.md
site/src/components/hero.js

Add call for session proposals

---

site/package.json
yarn.lock

Remove obsolete dependencies

---

site/content/events/call-for-proposals-2020.md

Add Dec 2019 webinar

---

site/content/posts/should-data-literacy-be-promoted.md

Add blog post (should-data-literacy-be-promoted)

---

site/content/posts/why-a-world-data-forum.md

Add blog post why-a-world-data-forum

---

site/content/posts/why-a-world-data-forum.md

Edit why-a-world-data-forum post

---

.github/workflows/code-qa.yml
package.json
yarn.lock

Enforce Node 10.x

---

README.md
package.json
sandbox.config.json

Add CodeSandbox support

---

.eslintrc
.prettierrc
gatsby-theme-2020/gatsby-config.js
gatsby-theme-profiles/gatsby-config.js
lint-staged.config.js
package.json
site/package.json
yarn.lock

Reconfigure lint and format tasks

---

now.json

Remove now.json

---

README.md
sandbox.config.json

Remove sandbox.config.json

---

package.json
yarn.lock

Remove now package

---

.github/dependabot.yml

Switch Dependabot updates to monthly

---

.devcontainer/.devcontainer.json
.devcontainer/Dockerfile
.vscode/extensions.json
.vscode/settings.json

Add container configs

---

microfrontends/profiles/package.json
microfrontends/profiles/src/@undataforum/gatsby-theme-profiles/i18n/translations/en.js
site/package.json
site/src/gatsby-plugin-theme-ui/index.js

Deep merge theme without deepmerge
